# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSR', '0015_auto_20170809_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='Course',
            field=models.ManyToManyField(through='RSR.PersonToCourse', to='RSR.Person'),
        ),
    ]
